### PR TITLE
Add PostgreSQL Multi Version CI Settings

### PR DESCRIPTION
**Pull request by tachikiH**
Added a feature implementing CI tools with GitHub Actions to perform regression testing on SQLite FDW across the five major versions of PostgreSQL.

### CODE REVIEW

**Comment by mkgrgis** [comment]
Thanks, @tachikiH ! If was very interesting for me to read you scripts. Do you think `git` miltiversional source codes getting way like in https://github.com/pgspider/fdw_testing_scripts is slower? Have you got any automated testing reports from github in you branches?

Also, maybe you can write `README_JP.md` ? In [PostgreSQL official documents](https://www.postgresql.org/docs/) there is ZH, FR, RU, JP versions also for `postgres_fdw`.

P. S. @t-kataym in main maintainer of this repository, I am only independent researcher.

**Comment by t-kataym** [comment]
@mkgrgis , @tachikiH is our project member and this is a prototype.  
There are points to be improved, and we will fix and release in the next year.
The testing time is only several minutes.

This is just CI on GitHub. On the other hand, fdw_testing_scripts you created is useful for testing on a local machine and debugging, I think.

**Comment by mkgrgis** [comment]
Thanks for clarification, @t-kataym ! In this PR there is interesting undocumented in README.md [SQLite installation script](https://github.com/pgspider/sqlite_fdw/pull/92/files#diff-de56deb5407e5ec6c3c3047df3927d1e87a9e174ca2a741642aff903e81aa7be).
Look like for Ubuntu/Debian `--prefix='/usr'` for `./configure` also will be useful.
Also this CI will be very useful for contributors-beginners because this look like some form of guaranteed testing context in our case of not detailed testing documentation.

**Comment by mkgrgis** [comment]
@tachikiH , after https://github.com/pgspider/sqlite_fdw/pull/91/commits/cbba0432a2824c21912dc45f7b760ab4e350d54e and `/etc/fstab` line

> tmpfs  /tmp           tmpfs    defaults,noatime,nofail,mode=1777   0  0

 I have reduced test time to 20..30% of initial. Could you test this PR with `/tmp` as  _tmpfs_ on Github CI Ubuntu ?

**Comment by t-kataym** [comment]
Please let me merge this PR into "ci_settings" branch first, then continue to develop on this branch.

> I have reduced test time to 20..30% of initial. Could you test this PR with /tmp as tmpfs on Github CI Ubuntu ?

Thank you for your information.  
Could you tell me how to do so?

**Comment by mkgrgis** [comment]
> Could you tell me how to do so?

`/tmp` was mounted as [tmpfs](https://www.kernel.org/doc/html/latest/filesystems/tmpfs.html), this means no disk IO during SQLite operations, just memory copying/modifying.

**Pull request merged**
